### ISSUE TITLE
Contradictory information about UNICODE characters

### ISSUE THREAD

**Issue by fmarier** [publicsuffix/publicsuffix.org#20]
On <https://www.publicsuffix.org/list/>:

The very first paragraph ends with:

> Please note that the list is encoded using UTF-8.

and the fifth bullet under *Specification* includes this note:

> (Note: the list uses Unicode, not Punycode forms, and is encoded using UTF-8.) 

On the other hand, the *Formal specification* section starts with the following:

> The domain and all rules must be canonicalized in the normal way for hostnames - lower-case, Punycode (RFC 3492).

Looking through the list, it seems like the bit in *Formal specification* is wrong (or outdated). Every punycode in the list is part of a comment. There are no entries using Punycodes.

**Comment by sleevi** [comment]
I’m not sure I understand what you see as conflicting or contradictory.
Could you provide a bit more detail?

The point of the formal specification is to ensure applications convert
both the list and the target entry using the same algorithm (e.g. IDNA2003,
2008, or UTS-41 Transitional). The list is stored in a way to permit that.

**Comment by dnsguru** [comment]
@fmarier thank you for reporting this but we will close the issue as a wontfix

The file format of the list is identified to be UTF-8 in order to ensure that those who import or use it are aware of this encoding, to avoid some of the compatibility issues when importing a text file (such as may occur with Excel or other programs) under a default encoding that may not handle double byte characters (ie Western ANSI) and end up with the odd character display or handling.

Here is a snippet of what the public_suffix_list.dat looks like when not loaded as UTF-8:

`
...

// IDN ccTLDs
--
// When submitting patches, please   maintain a sort by ISO 3166 ccTLD, then
// U-label, and follow this format:
// // A-Label ("<Latin   renderings>", <language name>[, variant info]) : <ISO 316
// // [sponsoring org]
// U-Label
 
// xn--mgbaam7a8h ("Emerat",   Arabic) : AE
//   http://nic.ae/english/arabicdomain/rules.jsp
**Ø§Ù…Ø§Ø±Ø§Øª**
 
// xn--y9a3aq ("hye", Armenian)   : AM
// ISOC AM (operated by .am Registry)
**Õ°Õ¡Õµ**
 
// xn--54b7fta0cc ("Bangla",   Bangla) : BD
**à¦¬à¦¾à¦‚à¦²à¦¾**
 
// xn--90ae ("bg", Bulgarian) :   BG
**Ð±Ð³**
 
// xn--90ais ("bel",   Belarusian/Russian Cyrillic) : BY
// Operated by .by registry
**Ð±ÐµÐ»**
 
// xn--fiqs8s   ("Zhongguo/China", Chinese, Simplified) : CN
// CNNIC
//   http://cnnic.cn/html/Dir/2005/10/11/3218.htm
**ä¸­å›½**
 
// xn--fiqz9s   ("Zhongguo/China", Chinese, Traditional) : CN
// CNNIC
//   http://cnnic.cn/html/Dir/2005/10/11/3218.htm
**ä¸­åœ‹**
 
...
`

IDN TLDs are stored in their native 'U-Label' form, and we also include the punycode "A-Label" form in the comment for clarity in troubleshooting or diagnostics, as it eliminates any confusion about which IDN TLD may require attention, as sometimes there is variation introduced by the OS, Program, or other systems when composing or encoding the U-Label that is never present in the unique A-Label.

I hope that clarifies everything.

**Comment by fmarier** [comment]
I see. I though that the formal specification was instructing users to convert their domains to Punycode before trying to match against the list and I assumed it was because an earlier version of the list was encoded using Punycode instead of UTF-8.

I have proposed #21 to make this clearer. If you don't think it's necessary, feel free to close that PR and this issue. Thanks again for the extra clarifications.
